import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createHash } from "node:crypto";
import { runBatchCardinalityDiagnostic } from "../../../src/application/gmgn/wallet-stats-batch-cardinality-diagnostic.js";

const ALPHABET="123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
function base58(bytes: Uint8Array): string { let value=0n; for(const b of bytes)value=value*256n+BigInt(b); let out=""; while(value>0n){const r=Number(value%58n);out=ALPHABET[r]+out;value/=58n;} let zeros=0;while(zeros<bytes.length&&bytes[zeros]===0){out="1"+out;zeros++;}return out||"1"; }
function sha(value: Uint8Array|string){return createHash("sha256").update(value).digest("hex").toUpperCase();}
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"gmgn-cardinality-"));const wallets=Array.from({length:20},(_,i)=>{const b=new Uint8Array(32);b[31]=i+1;return base58(b);});const txt=Buffer.from(wallets.join("\n")+"\n");const labels=Buffer.from("{}");fs.writeFileSync(path.join(dir,"sol_addresses.txt"),txt);fs.writeFileSync(path.join(dir,"sol_address_labels.json"),labels);return{dir,wallets,txtHash:sha(txt),labelsHash:sha(labels),cleanup:()=>fs.rmSync(dir,{recursive:true,force:true})};}
function isolation(){return{root:"x",home:"x",cwd:"x",cleanup(){}};}
test("hash mismatch fails closed before execution",async()=>{const f=fixture();try{let calls=0;const r=await runBatchCardinalityDiagnostic({inputDir:f.dir,expectedHashes:{solAddressesTxtHash:"bad",solAddressLabelsJsonHash:f.labelsHash},dependencies:{createIsolation:isolation,execute:async()=>{calls++;return{exitCode:0,stdout:"{}",stderr:""};}}});assert.equal(r.status,"FAIL_CLOSED");assert.equal(r.requestBudgetUsed,0);assert.equal(calls,0);}finally{f.cleanup();}});
test("missing API key parks before execution",async()=>{const f=fixture();try{let calls=0;const r=await runBatchCardinalityDiagnostic({inputDir:f.dir,runtimeEnvironment:{},expectedHashes:{solAddressesTxtHash:f.txtHash,solAddressLabelsJsonHash:f.labelsHash},dependencies:{createIsolation:isolation,execute:async()=>{calls++;return{exitCode:0,stdout:"{}",stderr:""};}}});assert.equal(r.status,"PARK");assert.equal(r.requestBudgetUsed,0);assert.equal(calls,0);}finally{f.cleanup();}});
test("single-record provider response is safely classified incomplete",async()=>{const f=fixture();try{let args:string[]=[];const r=await runBatchCardinalityDiagnostic({inputDir:f.dir,runtimeEnvironment:{GMGN_API_KEY:"secret",PATH:"x",SystemRoot:"x",WINDIR:"x"},expectedHashes:{solAddressesTxtHash:f.txtHash,solAddressLabelsJsonHash:f.labelsHash},dependencies:{createIsolation:isolation,execute:async inv=>{args=inv.args;return{exitCode:0,stdout:JSON.stringify({wallet:f.wallets[0],realized_profit:1}),stderr:""};}}});assert.equal(r.status,"INCOMPLETE");assert.equal(r.diagnosticCode,"gmgn_batch_response_incomplete");assert.equal(r.envelope?.requestedIdentityMatchCount,1);assert.equal(r.envelope?.requestedIdentityMissingCount,19);assert.equal(r.requestBudgetUsed,1);assert.equal(args.filter(x=>x==="--wallet").length,1);for(const wallet of f.wallets)assert.equal(JSON.stringify(r).includes(wallet),false);}finally{f.cleanup();}});
test("record-list response covering all wallets succeeds",async()=>{const f=fixture();try{const r=await runBatchCardinalityDiagnostic({inputDir:f.dir,runtimeEnvironment:{GMGN_API_KEY:"secret",PATH:"x",SystemRoot:"x",WINDIR:"x"},expectedHashes:{solAddressesTxtHash:f.txtHash,solAddressLabelsJsonHash:f.labelsHash},dependencies:{createIsolation:isolation,execute:async()=>({exitCode:0,stdout:JSON.stringify({data:f.wallets.map(wallet=>({wallet}))}),stderr:""})}});assert.equal(r.status,"SUCCESS");assert.equal(r.envelope?.responseCoversAllRequestedWallets,true);}finally{f.cleanup();}});
