import type { Pool } from "pg";
import type { MacroG2Store } from "../../application/macro-daily-g2-run-service.js";
export class PostgresMacroDailyRepository implements MacroG2Store {
  constructor(private readonly pool: Pool) {}
  async findQuery(blueprintId: string, sqlSha256: string): Promise<{ queryId: number } | null> { const result = await this.pool.query<{ query_id: string }>("SELECT query_id FROM macro_query_registry WHERE blueprint_id=$1 AND sql_sha256=$2", [blueprintId, sqlSha256]); const row = result.rows[0]; return row ? { queryId: Number(row.query_id) } : null; }
  async save(input: { queryId: number; sqlSha256: string; reportDay: string; transactionCount: number; sourceAsOf: Date; resultSha256: string; briefSha256: string; deliveryMode: "dry_run" | "hermes_sent" }): Promise<void> {
    const client = await this.pool.connect(); try { await client.query("BEGIN"); await client.query("INSERT INTO macro_query_registry (blueprint_id, query_id, sql_sha256, query_version) VALUES ('G2_btc_tx_count',$1,$2,$3) ON CONFLICT (blueprint_id) DO UPDATE SET query_id=EXCLUDED.query_id, sql_sha256=EXCLUDED.sql_sha256, query_version=EXCLUDED.query_version, last_verified_at=now()", [input.queryId, input.sqlSha256, `saved:G2_btc_tx_count@${input.sqlSha256}`]); await client.query("INSERT INTO macro_daily_global_metrics (report_day,metric_name,subject,value,unit,source,query_ref,query_version,source_as_of,computed_at,completeness,warnings) VALUES ($1,'btc_transaction_count','bitcoin',$2,'count','dune',$3,$4,$5,now(),1,'[]'::jsonb) ON CONFLICT DO NOTHING", [input.reportDay,input.transactionCount,`dune:query:${input.queryId}`,`saved:G2_btc_tx_count@${input.sqlSha256}`,input.sourceAsOf]); await client.query("INSERT INTO macro_daily_delivery_runs (report_day,blueprint_id,result_sha256,source_as_of,brief_sha256,delivery_mode) VALUES ($1,'G2_btc_tx_count',$2,$3,$4,$5) ON CONFLICT DO NOTHING",[input.reportDay,input.resultSha256,input.sourceAsOf,input.briefSha256,input.deliveryMode]); await client.query("COMMIT"); } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
  }
}
